### ISSUE TITLE
Careful! pictures (image_urls)  in metadata might not corespond to pictures that were actually labeled

### ISSUE THREAD

**Issue by i008** [eBay/modanet#1]
I was exploring the dataset and found a very huge (5-20%) amount of misslabeled samples.
From my quick  research of the problem i found out that the image_url provided in the metadata does not  link to the image that was actually labeled.
I think it happens when post_url contains multiple pictures. But im not yet sure if this is true 100% of the time.
Here is a notebook pic with examples of the problem:

https://imgur.com/a/gLUxxR0
The notebook should make it clear.

I will try to check out if actually getting the images by scraping the post_url (and always getting the first image ) instead of  downloading using the url will solve the problem

**Comment by hrsma2i** [comment]
I fix the mismatch https://github.com/hrsma2i/modanet.

**Comment by hrsma2i** [comment]
@i008 I fixed the mismatch. https://github.com/hrsma2i/modanet#setup
And check https://github.com/hrsma2i/modanet/blob/master/ModaNet.ipynb

**Comment by i008** [comment]
Thanks @hrsma2i !

**Comment by bittnt** [comment]
Please check the update from paperdoll data set for the full image list: ```https://github.com/kyamagu/paperdoll/tree/master/data/chictopia```
