### ISSUE TITLE
Matching with Paperdoll images

### ISSUE THREAD

**Issue by alexrame** [eBay/modanet#2]
I am exploring the dataset, and I can not find all training images in the paperdoll dataset.
I am assuming that the matching between Modanet and Paperdoll is based on the id of the images.

Among the 52377 training images, 32413 of them are included in paperdoll, for example
- {'file_name': '0655364.jpg', 'license': 3, 'height': 600, 'width': 400, 'id': 655364}
matches with
{'post_url': 'http://www.chictopia.com/photo/show/584805', 'url': 'http://images1.chictopia.com/photos/DailyFashionista/5496701252/6589588537/black-reindeer-vintage-sweater-black-dolce-vita-shoes_400.jpg', 'id': 655364}
- {'file_name': '0524293.jpg', 'license': 3, 'height': 600, 'width': 400, 'id': 524293}
matches with
{'post_url': 'http://www.chictopia.com/photo/show/471733', 'url': 'http://images0.chictopia.com/photos/LisaMarieF/7769599330/heather-gray-francescas-shirt-camel-rachel-zoe-purse-light-blue-express-shor_400.jpg', 'id': 524293}
- {'file_name': '0393224.jpg', 'license': 3, 'height': 600, 'width': 400, 'id': 393224}
matches with
{'post_url': 'http://www.chictopia.com/photo/show/457562', 'url': 'http://images0.chictopia.com/photos/courtandhudson/1425342853/yellow-skirt-chartreuse-top_400.jpg', 'id': 393224}

However 19964 of them are missing, including for following lines
- {'file_name': '0000003.jpg', 'license': 3, 'height': 600, 'width': 400, 'id': 3}
- {'file_name': '0393220.jpg', 'license': 3, 'height': 600, 'width': 400, 'id': 393220}
- {'file_name': '0655363.jpg', 'license': 3, 'height': 600, 'width': 400, 'id': 655363}
- {'file_name': '0131080.jpg', 'license': 3, 'height': 600, 'width': 400, 'id': 131080}
- {'file_name': '0262155.jpg', 'license': 3, 'height': 600, 'width': 400, 'id': 262155}
- {'file_name': '0000013.jpg', 'license': 3, 'height': 600, 'width': 400, 'id': 13}
- {'file_name': '0524311.jpg', 'license': 3, 'height': 600, 'width': 400, 'id': 524311}
- {'file_name': '0786458.jpg', 'license': 3, 'height': 600, 'width': 400, 'id': 786458}
- {'file_name': '0131098.jpg', 'license': 3, 'height': 600, 'width': 400, 'id': 131098}
- {'file_name': '0131102.jpg', 'license': 3, 'height': 600, 'width': 400, 'id': 131102}

My paperdoll metadata is "data/paperdoll_dataset.mat" from data-v1.0.tar, downloaded from http://vision.is.tohoku.ac.jp/~kyamagu/research/paperdoll/

Thank you

**Comment by bittnt** [comment]
Please check the update from paperdoll data set for the full image list: ```https://github.com/kyamagu/paperdoll/tree/master/data/chictopia```
