### ISSUE TITLE
Facing issue  where to get this file'../PaperDoll/labels/paperdoll.json'

### ISSUE THREAD

**Issue by imSrbh** [eBay/modanet#6]
where to get this paperdoll.json in https://github.com/hrsma2i/modanet/blob/master/ModaNet.ipynb

json_file = '../PaperDoll/labels/paperdoll.json'
df_ppdl = pd.read_json(json_file)
df_ppdl

**Comment by bittnt** [comment]
Please refer to the paperdoll dataset to acquire the images for the ModaNet dataset:
https://github.com/kyamagu/paperdoll/tree/master/data/chictopia
