### ISSUE TITLE
No segmentation masks in validation set

### ISSUE THREAD

**Issue by ghost** [eBay/modanet#9]
Hey,

i'm currently trying to train a Mask R-CNN model on the ModaNet dataset
and realised that the validation set contains no polygon annotations.
For that reason i'm not able to complete validation at the end of each epoch.

Were they left out on purpose?

Thanks

**Comment by cad0p** [comment]
they are there for the challenge (challenge seems dead now though)

a solution i adopted was splitting the set into test, val and train 

i have developed a program that does just that if you need it

**Comment by ghost** [comment]
Hey @cad0p 
yeah I used the same approach of splitting the train set into train and val.
I've noticed your Mask-RCNN repo. I'm currently working on my thesis and I'm using Mask-RCNN and Modanet as well. But I'm using [matterport/mask-RCNN](https://github.com/matterport/Mask_RCNN/). Their implementation required annotations in the validation set; at least the way I adopted it. 

Thanks for your reply. You answered my question, so i'll close this issue.

**Comment by cad0p** [comment]
Hi, I'm doing it for my undergraduate thesis too! Maybe we could compare the results of the two different implementations? You can contact me at piercarlo.cadoppi@studenti.unipr.it

**Comment by elvisdias** [comment]
Hey @damrath,

how did you go around that problem using the matterport mask-rcnn?

**Comment by elvisdias** [comment]
Hi @damrath, so interesting we are working on the same thing. 

Are you available for talking about it? challenges and results

[]'s
